### ISSUE TITLE
Allow policies by license expression

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode.io#166]
`gpl-2.0 WITH oracle-openjdk-classpath-exception-2.0` is reported as a warning if `gpl-2.0` if set to report warning. In such as case I would like to set a policy to state that `gpl-2.0 WITH oracle-openjdk-classpath-exception-2.0` is OK and not warning and I am not sure  I can do this.

**Comment by tdruez** [comment]
Both the policy file and the database implementation of the feature are based on license key at the moment.

We will have to rethink those implementations to support license expression:

- Policy file:
```
-   license_key: mpl-2.0
    label: Restricted License
    compliance_alert: warning
```

- Policy in the CodebaseResource model:
```
for license_data in codebase_resource.licenses:
    key = license_data.get("key")
    license_data["policy"] = policies_index.get(key, None)
```

**Comment by aalexanderr** [comment]
How should policies by license expression work?
Should they be defined in different manner in policies.yaml? Example:
   ```
       license_expression_policies:
       -   license_expr: bsd-simplified AND gpl-2.0
           label: Restricted License
           compliance_alert: warning
    ```
and then be matched 1:1?
